name: Deploy to Windows EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Copy files to Windows EC2 via WinRM
      uses: jakejarvis/winrm-copy@v1
      with:
        host: ${{ secrets.EC2_WIN_HOST }}
        username: ${{ secrets.EC2_WIN_USER }}
        password: ${{ secrets.EC2_WIN_PASSWORD }}
        source: "./"
        destination: "C:\\Dotnet-app"
        protocol: https

    - name: Run Deployment Script on Windows
      uses: jakejarvis/winrm-exec@v1
      with:
        host: ${{ secrets.EC2_WIN_HOST }}
        username: ${{ secrets.EC2_WIN_USER }}
        password: ${{ secrets.EC2_WIN_PASSWORD }}
        protocol: https
        command: |
          powershell -Command "cd 'C:\Dotnet-app'; ./your-deploy-script.ps1"
