name: Deploy to Windows EC2 via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Upload files to Windows EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_SSH_HOST }}
        username: ${{ secrets.EC2_SSH_USER }}
        password: ${{ secrets.EC2_SSH_PASSWORD }}
        source: "."
        target: "C:/Dotnet-app"

    - name: Execute deployment script on Windows EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_SSH_HOST }}
        username: ${{ secrets.EC2_SSH_USER }}
        password: ${{ secrets.EC2_SSH_PASSWORD }}
        script: |
          cd C:\Dotnet-app
          powershell -ExecutionPolicy Bypass -File .\your-deploy-script.ps1
