name: Build and Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Change to a Windows runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet publish -c Release -o ./publish

  deploy:
    runs-on: windows-latest  # Change to a Windows runner
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Files to EC2 Instance
        shell: pwsh
        run: |
          $session = New-PSSession -ComputerName 18.141.196.254 -Credential (New-Object System.Management.Automation.PSCredential("administrator", (ConvertTo-SecureString "${{ secrets.EC2_PASSWORD }}" -AsPlainText -Force))) -Authentication Negotiate
          Invoke-Command -Session $session -ScriptBlock {
              if (!(Test-Path 'C:\Dotnet-app')) { New-Item -Path 'C:\Dotnet-app' -ItemType Directory }
              Copy-Item -Path '$(System.DefaultWorkingDirectory)\publish\*' -Destination 'C:\Dotnet-app' -Force
          }
          Remove-PSSession -Session $session 
