name: Build and Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet publish -c Release -o ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Enable RDP
        uses: gbraad-actions/enable-remote-desktop@v1
        with:
          host: 3.0.98.56
          username: administrator
          password: ${{ secrets.EC2_PASSWORD }} # Use a secret for sensitive data

      - name: Copy Files to EC2 Instance
        run: |
          $session = New-PSSession -ComputerName 3.0.98.56 -Credential (New-Object System.Management.Automation.PSCredential("administrator", (ConvertTo-SecureString "${{ secrets.EC2_PASSWORD }}" -AsPlainText -Force))) -Authentication Negotiate
          Invoke-Command -Session $session -ScriptBlock {
              if (!(Test-Path 'C:\Dotnet-app')) { New-Item -Path 'C:\Dotnet-app' -ItemType Directory }
              Copy-Item -Path '$(System.DefaultWorkingDirectory)\publish\*' -Destination 'C:\Dotnet-app' -Force
          }
          Remove-PSSession -Session $session
